name: Solidity

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  contracts-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build contracts
        run: npm run compile

      - name: Run tests
        run: npm run test
